AdminPassword=
AdminUserName=
JDBC.CLICCDatasource.PasswordEncrypted=
JDBC.CLICCDatasource.user.Value=CLICCIPTV_QV1
JDBC.EIFESBDatasource.PasswordEncrypted=
JDBC.EIFESBDatasource.user.Value=EIFAPP_ESB
JDBC.ESBAppDatasource.PasswordEncrypted=
JDBC.ESBAppDatasource.user.Value=QA9APPESB
JDBC.LocalSvcTblDataSource.PasswordEncrypted=
JDBC.LocalSvcTblDataSource.user.Value=RESPESBDSFT4_STB
JDBC.O911DB.PasswordEncrypted=
JDBC.O911DB.user.Value=ROP02_CICSK
JDBC.OraSDPMDataSource.PasswordEncrypted=
JDBC.OraSDPMDataSource.user.Value=RESPESBDSFT4_UMS
JDBC.SOADataSource.PasswordEncrypted=
JDBC.SOADataSource.user.Value=RESPESBDSFT4_SOAINFRA
JDBC.SOALocalTxDataSource.PasswordEncrypted=
JDBC.SOALocalTxDataSource.user.Value=RESPESBDSFT4_SOAINFRA
JDBC.WLSSchemaDataSource.PasswordEncrypted=
JDBC.WLSSchemaDataSource.user.Value=RESPESBDSFT4_WLS_RUNTIME
JDBC.dsDTV.PasswordEncrypted=
JDBC.dsDTV.user.Value=QA9TDVESB
JDBC.mds-owsm.PasswordEncrypted=
JDBC.mds-owsm.user.Value=RESPESBDSFT4_MDS
JDBC.opss-audit-DBDS.PasswordEncrypted=
JDBC.opss-audit-DBDS.user.Value=RESPESBDSFT4_IAU_APPEND
JDBC.opss-audit-viewDS.PasswordEncrypted=
JDBC.opss-audit-viewDS.user.Value=RESPESBDSFT4_IAU_VIEWER
JDBC.opss-data-source.PasswordEncrypted=
JDBC.opss-data-source.user.Value=RESPESBDSFT4_OPSS
JDBC.wlsbjmsrpDataSource.PasswordEncrypted=
JDBC.wlsbjmsrpDataSource.user.Value=RESPESBDSFT4_SOAINFRA
JMS.NGPPJmsSAFModule.NGPPJmsSAFRemoteContextURL1.PasswordEncrypted=
JMS.NGPPJmsSAFModule.NGPPJmsSAFRemoteContextURL1.Username=it_eif_esb
SecurityConfig.NodeManagerPasswordEncrypted=
Server.SFT9RESPESBD_MS01.CustomIdentityKeyStorePassPhraseEncrypted=
Server.SFT9RESPESBD_MS01.CustomTrustKeyStorePassPhraseEncrypted=
Server.SFT9RESPESBD_MS01.PasswordEncrypted=
Server.SFT9RESPESBD_MS01.SSL.ServerPrivateKeyPassPhraseEncrypted=
Server.SFT9RESPESBD_MS01.Username=weblogic
