kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /home/jay/kind-data
        containerPath: /home/jay/kind-data
        readOnly: false
      - hostPath: /home/jay/artifacts
        containerPath: /home/jay/artifacts
        readOnly: false