apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weblogic-pvc
  namsespace: soans
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-ceph-rbd