apiVersion: v1
kind: PersistentVolume
metadata:
  name: soainfra-domain-pv
  labels:
    weblogic.domainUID: soainfra
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/home/jay/kind-data/SOA"
