kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: soainfra-domain-pvc
  namespace: soans
  labels:
    weblogic.domainUID: soainfra
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi