apiVersion: v1
kind: PersistentVolume
metadata:
  name: soainfra-deploy-artifacts-pv
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/home/jay/artifacts"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: soainfra-deploy-artifacts-pvc
  namespace: soans
spec:
  storageClassName: standard
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi