# Copyright (c) 2020, 2022, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
#
# This is a template for RCU Pod
#
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: rcu
  name: rcu
  namespace: soans
spec:
  containers:
  - args:
    - sleep
    - infinity
    image: container-registry.oracle.com/middleware/soasuite:14.1.2.0-jdk21-ol8-241205
    imagePullPolicy: IfNotPresent
    name: rcu
    volumeMounts:
    - name: rcu-secret-volume
      mountPath: "/rcu-secret"
      readOnly: true
  volumes:
  - name: rcu-secret-volume
    secret:
      secretName: oracle-rcu-secret
  #imagePullSecrets:
  #- name: none

